Update docker-publish.yml

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -31,19 +31,25 @@ jobs:
           docker build -t unpast:${{ github.event.inputs.tag }} .
           docker tag unpast:${{ github.event.inputs.tag }} unpast:latest
 
+          - name: Set up results directory with permissions
+          run: |
+            mkdir -p results
+            chmod -R 777 results
+
       - name: Run unpast command inside Docker container
         run: |
-          docker run --rm -v "${{ github.workspace }}":/app --entrypoint bash unpast:${{ github.event.inputs.tag }} -c "
-            cd /app && \
-            sudo mkdir -p results && \
-            sudo chmod -R 777 results && \
-            unpast --exprs /app/unpast/tests/scenario_B500.exprs.tsv.gz --basename results/scenario_B500 --verbose && \
-            ls -l results && \
-            OUTPUT_FILE=\$(ls results/scenario_B500*_*biclusters.tsv) && \
-            if [ ! -s \"\$OUTPUT_FILE\" ]; then
-              echo 'Test failed: Output file is missing or empty' && exit 1
-            fi"
-
+          docker run --rm -v "${{ github.workspace }}":/data unpast:${{ github.event.inputs.tag }} bash -c "
+            cd /data && unpast --exprs unpast/tests/scenario_B500.exprs.tsv.gz --basename results/scenario_B500 --verbose"
+          
+      - name: Verify Output
+        run: |
+          ls -l results
+          OUTPUT_FILE=$(ls results/scenario_B500*_*biclusters.tsv)
+          if [ ! -s "$OUTPUT_FILE" ]; then
+            echo "Test failed: Output file is missing or empty"
+            exit 1
+          fi
+  
       - name: Push Docker images to Docker Hub
         if: ${{ success() }}
         run: |
